import type { KnowledgeLocale } from '../../services/ai.service';

const copy = {
  open: ['開啟 Corely Claw ERP 助手', 'Open Corely Claw ERP assistant'],
  close: ['關閉助手', 'Close assistant'],
  greeting: ['跟 Claw 打招呼', 'Say hello to Claw'],
  guides: ['操作指南', 'Product guides'],
  chat: ['AI 問答', 'AI chat'],
  mode: ['ERP 使用指南與 AI 助手', 'ERP guides and AI assistant'],
  company: ['目前公司', 'Current company'],
  chooseCompany: ['選擇查詢公司', 'Choose a company'],
  companyError: ['無法載入公司範圍，請關閉後重新開啟助手。', 'Unable to load company access. Close and reopen the assistant.'],
  welcome: ['一起把工作變簡單', 'Let’s make work simpler'],
  intro: ['選一個主題，我帶你找到設定位置；也可以切換 AI 問答，查詢你有權限的資料。', 'Choose a guide to find the right settings, or ask AI about data you can access.'],
  browse: ['瀏覽全部指南', 'Browse all guides'],
  home: ['回到指南首頁', 'Back to guide home'],
  back: ['回到指南清單', 'Back to guides'],
  search: ['搜尋費用、權限、庫存、設定…', 'Search expenses, access, inventory, settings…'],
  searchLabel: ['搜尋操作指南', 'Search product guides'],
  results: ['相關使用說明', 'Related guides'],
  all: ['全部主題', 'All topics'],
  category: ['指南分類', 'Guide category'],
  empty: ['沒有找到相關說明，試試功能名稱，或瀏覽全部指南。', 'No matching guide. Try a feature name or browse all guides.'],
  inaccessible: ['這篇指南目前無法使用，可能已更新或不在你的權限範圍。', 'This guide may have changed or is outside your access.'],
  navigate: ['前往功能', 'Open feature'],
  examples: ['格式範例與下載', 'Examples and downloads'],
  exampleNote: ['範例使用合成資料，下載後請自行核對；不會匯入或更動系統資料。', 'Examples contain synthetic data. Review before use; downloading does not import or change records.'],
  invalidExample: ['這個範例格式無法安全下載。', 'This example cannot be downloaded safely.'],
  sources: ['文件來源與版本', 'Sources and version'],
  version: ['文件版本', 'Document version'],
  updated: ['查核時間', 'Checked at'],
  readOnly: ['指南與唯讀查詢，不會自動審批或付款。', 'Guides and read-only queries. No automatic approval or payment.'],
  loading: ['正在載入你可使用的指南…', 'Loading guides you can access…'],
  retry: ['重新載入', 'Try again'],
  unauthorized: ['登入已失效，請重新登入。', 'Your session expired. Please sign in again.'],
  forbidden: ['目前沒有這個內容或公司資料的查詢權限。請確認權限或切換公司。', 'You do not have access to this content or company data. Check access or switch company.'],
  invalid: ['查詢條件無法使用，請縮短問題或確認日期。', 'Check the query, shorten your question or verify the dates.'],
  unavailable: ['目前無法完成查詢，請稍後重試。', 'The query could not be completed. Please try again.'],
  aiOffline: ['AI 尚未開放連線，操作指南仍可使用。', 'AI is not connected. Product guides are still available.'],
  aiStatusError: ['無法確認 AI 連線狀態，請重試。', 'Unable to check AI availability. Please retry.'],
  aiModel: ['AI 模式', 'AI model'],
  clear: ['清除這段對話', 'Clear this conversation'],
  chatWelcome: ['從一個問題開始', 'Start with a question'],
  chatHint: ['詢問操作方式，或查詢目前公司內你有權限的資料。', 'Ask how to use ERP or query information you can access in this company.'],
  promptPage: ['這個頁面可以做什麼？', 'What can I do on this page?'],
  promptExpense: ['如何申請費用並交給主管審核？', 'How do I submit an expense for manager approval?'],
  promptAccess: ['如何設定人員能看到的功能？', 'How do I configure which features a person can access?'],
  promptTotal: ['本月我的費用申請總額是多少？', 'What is my total expense amount this month?'],
  you: ['你', 'You'],
  unfinished: ['尚未完成', 'Not completed'],
  liveData: ['即時資料查詢', 'Live data query'],
  thinking: ['正在確認權限並整理資料…', 'Checking access and preparing the answer…'],
  question: ['輸入問題，例如：怎麼申請費用？', 'Ask a question, such as how to submit an expense'],
  send: ['送出', 'Send'],
} as const;

export type CopyKey = keyof typeof copy;
export function clawText(locale: KnowledgeLocale, key: CopyKey): string {
  return copy[key][locale === 'en' ? 1 : 0];
}
